// Generated by https://quicktype.io

export interface TopLevel {
  id_articulo?: number;
  articulo?: string;
  imagen?: string;
  descripcion?: string;
}

export interface News {
  title?: string;
  description?: string;
  urlToImage?: string;
}
